### ISSUE TITLE
Report a bug can't deal with error confirmation requests

### ISSUE THREAD

**Issue by hinerm** [fiji/Bug_Submitter#4]
It's possible for the `post_bug.cgi` script to throw an error:

```
  <div class="throw_error">
    It looks like you didn't come from the right page (you have no valid token for
    the <em>create_bug</em> action while processing the
    'post_bug.cgi' script). The reason could be one of:<br>
    <ul>
      <li>You clicked the "Back" button of your web browser after having successfully
      submitted changes, which is generally not a good idea (but harmless).</li>
      <li>You entered the URL in the address bar of your web browser directly,
      which should be safe.</li>
      <li>You clicked on a URL which redirected you here <b>without your consent</b>,
      in which case this action is much more critical.</li>
    </ul>
    Are you sure you want to commit these changes anyway? This may result in
    unexpected and undesired results.
  </div>
```

This isn't handled by Fiji, so it just makes users unable to report bugs via Fiji.

**Comment by ctrueden** [comment]
The long-term plan is to create a new issue reporting system, which interfaces with GitHub issues. It could live in scijava-common, or a scijava-issues component if there are new dependencies. And a UI would exist in scijava-ui-swing. The issue reporter would support reporting bugs against components (i.e., JAR files) which have embedded Maven POMs that specify an `issueManagement` section with a compatible issue tracker. And of course there would be reasonable defaults—e.g., ImageJ would be configured to use `imagej/imagej` by default if the user does not specify a component.
